$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1442816072482.61),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e5b0540c36c94a418967ddbe349f2ccd",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a85dd6ce377a400abcb284a7e9c21800",
          "label":"1",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"9598a8fe27184867a38b9a6950ca2444",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3a5ad020c7f241db9620d4e2e150bdd8",
                  "label":"",
                  "parentDynamicPanel":"a85dd6ce377a400abcb284a7e9c21800",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "size":{
                      "width":300,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e9c423b864f04498a855ad9997f4b65b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a85dd6ce377a400abcb284a7e9c21800",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "size":{
                          "width":300,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u1.png"}},
{
                  "id":"03678ef50c55489ebf27e9c3218994f4",
                  "label":"",
                  "parentDynamicPanel":"a85dd6ce377a400abcb284a7e9c21800",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0.3",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "size":{
                      "width":300,
                      "height":60},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d7cd2aaabdf7438c8d8c7085edb1e2cc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a85dd6ce377a400abcb284a7e9c21800",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0.3",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "size":{
                          "width":300,
                          "height":60},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 1 到 状态2",
                              "panelsToStates":[{
                                  "panelPath":["a85dd6ce377a400abcb284a7e9c21800"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u3.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"f8161b10449a48d68152baec6488ee5a",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b7d55c4309b540a1a9c6f8c93bc7b93f",
                  "label":"",
                  "parentDynamicPanel":"a85dd6ce377a400abcb284a7e9c21800",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "size":{
                      "width":300,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d53c96273ccb4999a923b0dfd70e919e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"a85dd6ce377a400abcb284a7e9c21800",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "size":{
                          "width":300,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 1 到 状态1",
                              "panelsToStates":[{
                                  "panelPath":["a85dd6ce377a400abcb284a7e9c21800"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u1.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"612a157e12634753b63e047dbc99191f",
          "label":"2",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":70},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"ef11480f2b8e435b9aa13daf85d7ea33",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"99983399306246cba3cc64f2775b5034",
                  "label":"",
                  "parentDynamicPanel":"612a157e12634753b63e047dbc99191f",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "size":{
                      "width":300,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fb127ed8c34e43b3a9df332e18732f0a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"612a157e12634753b63e047dbc99191f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "size":{
                          "width":300,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u8.png"}},
{
                  "id":"c0432a95eac6415c95cb147c824f52d7",
                  "label":"",
                  "parentDynamicPanel":"612a157e12634753b63e047dbc99191f",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0.3",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "size":{
                      "width":300,
                      "height":60},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a5990c7257e6444999f700c47c2bc598",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"612a157e12634753b63e047dbc99191f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0.3",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "size":{
                          "width":300,
                          "height":60},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 2 到 状态2",
                              "panelsToStates":[{
                                  "panelPath":["612a157e12634753b63e047dbc99191f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u3.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"a72e0559fe504e91b687b85fdd0c66ed",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"45c773aac71248b692dc3f26caaff826",
                  "label":"",
                  "parentDynamicPanel":"612a157e12634753b63e047dbc99191f",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "size":{
                      "width":300,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2e85c3d265f642a980decc26d3ff5d3d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"612a157e12634753b63e047dbc99191f",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "size":{
                          "width":300,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 2 到 状态1",
                              "panelsToStates":[{
                                  "panelPath":["612a157e12634753b63e047dbc99191f"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u8.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"f6acb856467642e4abe0e28a0cbb0a1e",
          "label":"3",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":140},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"9633ce98467a4cd8b6964a3455c5633d",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"cd6bd29e3d4d44088e0f1e41919e1618",
                  "label":"",
                  "parentDynamicPanel":"f6acb856467642e4abe0e28a0cbb0a1e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "size":{
                      "width":300,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f072a5e98b3c424685b091fabab0f496",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f6acb856467642e4abe0e28a0cbb0a1e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "size":{
                          "width":300,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u15.png"}},
{
                  "id":"ab6fa6ac23cb49e6b977b15ad77419cc",
                  "label":"",
                  "parentDynamicPanel":"f6acb856467642e4abe0e28a0cbb0a1e",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "opacity":"0.3",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "size":{
                      "width":300,
                      "height":60},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9740ec5939ba49d1955c16d1d71f5304",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f6acb856467642e4abe0e28a0cbb0a1e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "opacity":"0.3",
                        "fill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "size":{
                          "width":300,
                          "height":60},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 3 到 状态2",
                              "panelsToStates":[{
                                  "panelPath":["f6acb856467642e4abe0e28a0cbb0a1e"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u3.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"0aba1e08d2474a47b2301a840bcef44d",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"59cf61dc4a444c36842a3c8882413b77",
                  "label":"",
                  "parentDynamicPanel":"f6acb856467642e4abe0e28a0cbb0a1e",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "fontSize":"16px",
                    "size":{
                      "width":300,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"66e651c76b724986bf71721b33d8d478",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"f6acb856467642e4abe0e28a0cbb0a1e",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"16px",
                        "size":{
                          "width":300,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 3 到 状态1",
                              "panelsToStates":[{
                                  "panelPath":["f6acb856467642e4abe0e28a0cbb0a1e"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/u15.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "a85dd6ce377a400abcb284a7e9c21800":{
      "scriptId":"u0"},
    "3a5ad020c7f241db9620d4e2e150bdd8":{
      "scriptId":"u1"},
    "e9c423b864f04498a855ad9997f4b65b":{
      "scriptId":"u2"},
    "03678ef50c55489ebf27e9c3218994f4":{
      "scriptId":"u3"},
    "d7cd2aaabdf7438c8d8c7085edb1e2cc":{
      "scriptId":"u4"},
    "b7d55c4309b540a1a9c6f8c93bc7b93f":{
      "scriptId":"u5"},
    "d53c96273ccb4999a923b0dfd70e919e":{
      "scriptId":"u6"},
    "612a157e12634753b63e047dbc99191f":{
      "scriptId":"u7"},
    "99983399306246cba3cc64f2775b5034":{
      "scriptId":"u8"},
    "fb127ed8c34e43b3a9df332e18732f0a":{
      "scriptId":"u9"},
    "c0432a95eac6415c95cb147c824f52d7":{
      "scriptId":"u10"},
    "a5990c7257e6444999f700c47c2bc598":{
      "scriptId":"u11"},
    "45c773aac71248b692dc3f26caaff826":{
      "scriptId":"u12"},
    "2e85c3d265f642a980decc26d3ff5d3d":{
      "scriptId":"u13"},
    "f6acb856467642e4abe0e28a0cbb0a1e":{
      "scriptId":"u14"},
    "cd6bd29e3d4d44088e0f1e41919e1618":{
      "scriptId":"u15"},
    "f072a5e98b3c424685b091fabab0f496":{
      "scriptId":"u16"},
    "ab6fa6ac23cb49e6b977b15ad77419cc":{
      "scriptId":"u17"},
    "9740ec5939ba49d1955c16d1d71f5304":{
      "scriptId":"u18"},
    "59cf61dc4a444c36842a3c8882413b77":{
      "scriptId":"u19"},
    "66e651c76b724986bf71721b33d8d478":{
      "scriptId":"u20"}}});