$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1441712046831.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"b92e8bd8eb1e44e6914e9ef7744fdc05",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setFunction",
                "description":"设置 选中状态值 tab1 = &quot;true&quot;, 且<br> 选中状态值 不明 = &quot;false&quot;",
                "expr":{
                  "exprType":"block",
                  "subExprs":[{
                      "exprType":"fcall",
                      "functionName":"SetCheckState",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":false,
                          "isFocused":false,
                          "isTarget":false,
                          "value":["589a04a1b9e044b2a03f821a87c2034d"]},
{
                          "exprType":"stringLiteral",
                          "value":"true",
                          "stos":[]}]}]}}]}]}},
    "diagram":{
      "objects":[{
          "id":"7728297c2dc248ecac4268429fede26a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":640,
              "height":180},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c290448af3834d36a79175f5197647b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":640,
                  "height":180},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"589a04a1b9e044b2a03f821a87c2034d",
          "label":"tab1",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "stateStyles":{
              "mouseDown":{
},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF3399FF}}},
            "location":{
              "x":10,
              "y":5},
            "size":{
              "width":60,
              "height":20},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b45325e93804c81bd91e5245cca92f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "stateStyles":{
                  "mouseDown":{
},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF3399FF}}},
                "location":{
                  "x":10,
                  "y":5},
                "size":{
                  "width":60,
                  "height":20},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/tab1_u2.png",
            "selected~":"images/home/tab1_u2_selected.png"}},
{
          "id":"6b9d18157dc24af5a87528db93e49b86",
          "label":"项目日报",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":30},
            "size":{
              "width":630,
              "height":145}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"8a3e354c51cd4acd95a4deb941934dac",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"1d3cb3753cb94355b301ac5a5573acd4",
                  "label":"",
                  "parentDynamicPanel":"6b9d18157dc24af5a87528db93e49b86",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":630,
                      "height":145},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ba937a1ebf4b48b99042f1c1a1064ee3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6b9d18157dc24af5a87528db93e49b86",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":630,
                          "height":145},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u5.png"}},
{
                  "id":"2bd0db15ac3849caabbb9a1873a5b41b",
                  "label":"",
                  "parentDynamicPanel":"6b9d18157dc24af5a87528db93e49b86",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":10},
                    "size":{
                      "width":610,
                      "height":130}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"442c30d0335248e29d760926db24fff5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6b9d18157dc24af5a87528db93e49b86",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":10},
                        "size":{
                          "width":610,
                          "height":130}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"fb437406c6da45ddb2a3430e8660fbc5",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5c75cb118ffc4822b7b7b854ddac729e",
                  "label":"",
                  "parentDynamicPanel":"6b9d18157dc24af5a87528db93e49b86",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":630,
                      "height":145},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"173822f5b7194c349c4f2649523c0327",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6b9d18157dc24af5a87528db93e49b86",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":630,
                          "height":145},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u5.png"}},
{
                  "id":"b5097622ff2f469fbd87d0039c0bfb8a",
                  "label":"",
                  "parentDynamicPanel":"6b9d18157dc24af5a87528db93e49b86",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":10},
                    "size":{
                      "width":610,
                      "height":130}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"63babe7652f44b45b872cac1f96c039f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6b9d18157dc24af5a87528db93e49b86",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":10},
                        "size":{
                          "width":610,
                          "height":130}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"14d4e071874e49048c8770930952442c",
              "label":"状态3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"a4f0181e1fff49e3bafabe81d923a4d5",
                  "label":"",
                  "parentDynamicPanel":"6b9d18157dc24af5a87528db93e49b86",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":630,
                      "height":145},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"05c5258a9a3646e09184825847723f2b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6b9d18157dc24af5a87528db93e49b86",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":630,
                          "height":145},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u5.png"}},
{
                  "id":"2bccd85a9bb8488d85e6af95723ca9ea",
                  "label":"",
                  "parentDynamicPanel":"6b9d18157dc24af5a87528db93e49b86",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":10},
                    "size":{
                      "width":610,
                      "height":130}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"51f1eda2bb33421080358b2ffbdfaf79",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6b9d18157dc24af5a87528db93e49b86",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":10},
                        "size":{
                          "width":610,
                          "height":130}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"42af23f53cd14c90b030c7ba19ac5314",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":243,
              "y":4},
            "size":{
              "width":110,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"用例 1<br> (If 选中项值 当前部件 = &quot;孙耀祥&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"孙耀祥",
                      "stos":[]}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 项目日报 到 状态1",
                      "panelsToStates":[{
                          "panelPath":["6b9d18157dc24af5a87528db93e49b86"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"用例 2<br> (Else If 选中项值 当前部件 = &quot;李启明&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"李启明",
                      "stos":[]}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 项目日报 到 状态2",
                      "panelsToStates":[{
                          "panelPath":["6b9d18157dc24af5a87528db93e49b86"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]},
{
                  "description":"用例 3<br> (Else If 选中项值 当前部件 = &quot;张佳佳&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"张佳佳",
                      "stos":[]}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 项目日报 到 状态3",
                      "panelsToStates":[{
                          "panelPath":["6b9d18157dc24af5a87528db93e49b86"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":3,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}}},
{
          "id":"2bfa9e6ccbfb42fdb5c16993939f0f49",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":186,
              "y":7},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e15e0364bf5c4fcfa7884495c466901a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF666666,
                  "opacity":1},
                "location":{
                  "x":186,
                  "y":7},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "7728297c2dc248ecac4268429fede26a":{
      "scriptId":"u0"},
    "c290448af3834d36a79175f5197647b5":{
      "scriptId":"u1"},
    "589a04a1b9e044b2a03f821a87c2034d":{
      "scriptId":"u2"},
    "9b45325e93804c81bd91e5245cca92f1":{
      "scriptId":"u3"},
    "6b9d18157dc24af5a87528db93e49b86":{
      "scriptId":"u4"},
    "1d3cb3753cb94355b301ac5a5573acd4":{
      "scriptId":"u5"},
    "ba937a1ebf4b48b99042f1c1a1064ee3":{
      "scriptId":"u6"},
    "2bd0db15ac3849caabbb9a1873a5b41b":{
      "scriptId":"u7"},
    "442c30d0335248e29d760926db24fff5":{
      "scriptId":"u8"},
    "5c75cb118ffc4822b7b7b854ddac729e":{
      "scriptId":"u9"},
    "173822f5b7194c349c4f2649523c0327":{
      "scriptId":"u10"},
    "b5097622ff2f469fbd87d0039c0bfb8a":{
      "scriptId":"u11"},
    "63babe7652f44b45b872cac1f96c039f":{
      "scriptId":"u12"},
    "a4f0181e1fff49e3bafabe81d923a4d5":{
      "scriptId":"u13"},
    "05c5258a9a3646e09184825847723f2b":{
      "scriptId":"u14"},
    "2bccd85a9bb8488d85e6af95723ca9ea":{
      "scriptId":"u15"},
    "51f1eda2bb33421080358b2ffbdfaf79":{
      "scriptId":"u16"},
    "42af23f53cd14c90b030c7ba19ac5314":{
      "scriptId":"u17"},
    "2bfa9e6ccbfb42fdb5c16993939f0f49":{
      "scriptId":"u18"},
    "e15e0364bf5c4fcfa7884495c466901a":{
      "scriptId":"u19"}}});