$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1441680109476.98),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b435af52e2274a4b806dbf0df65a01a1",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c1d74e7502c8493383558ce868a91183",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF39B7C6},
            "location":{
              "x":5,
              "y":0},
            "size":{
              "width":195,
              "height":70},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"13"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff61c21f8ef94c0a990248e97b1b9c22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF39B7C6},
                "location":{
                  "x":5,
                  "y":0},
                "size":{
                  "width":195,
                  "height":70},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"13"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"a63955a06fe444a69428c0765d0a7306",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF52D58D},
            "location":{
              "x":215,
              "y":0},
            "size":{
              "width":195,
              "height":70},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"13"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"739bd77018804f65a0ac3933bf87dca5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF52D58D},
                "location":{
                  "x":215,
                  "y":0},
                "size":{
                  "width":195,
                  "height":70},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"13"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"bdefe8208ba34237b7e02e6cf7205743",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFF8000},
            "location":{
              "x":5,
              "y":80},
            "size":{
              "width":195,
              "height":70},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"13"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fd3c057c3d14bbc8eddf96071837bc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF8000},
                "location":{
                  "x":5,
                  "y":80},
                "size":{
                  "width":195,
                  "height":70},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"13"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"0de330046e6243d9a72347e946d71bf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFB7D100},
            "location":{
              "x":215,
              "y":80},
            "size":{
              "width":195,
              "height":70},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"13"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"408b4e0931c740d994ef57ed1a6a9de5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFB7D100},
                "location":{
                  "x":215,
                  "y":80},
                "size":{
                  "width":195,
                  "height":70},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"13"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c1d74e7502c8493383558ce868a91183":{
      "scriptId":"u0"},
    "ff61c21f8ef94c0a990248e97b1b9c22":{
      "scriptId":"u1"},
    "a63955a06fe444a69428c0765d0a7306":{
      "scriptId":"u2"},
    "739bd77018804f65a0ac3933bf87dca5":{
      "scriptId":"u3"},
    "bdefe8208ba34237b7e02e6cf7205743":{
      "scriptId":"u4"},
    "0fd3c057c3d14bbc8eddf96071837bc3":{
      "scriptId":"u5"},
    "0de330046e6243d9a72347e946d71bf1":{
      "scriptId":"u6"},
    "408b4e0931c740d994ef57ed1a6a9de5":{
      "scriptId":"u7"}}});