$axure.loadCurrentPage({
  "url":"page_1.html",
  "generationDate":new Date(1441902251616.33),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"3520e445ff5642ff849dde4ac21c8ac5",
    "type":"Axure:Page",
    "name":"Page 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[]}},
  "masters":{
},
  "objectPaths":{
}});