$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1451355589374.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"38d0eee1dbca4b34a00f11770512753f",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"wait",
                "description":"等待3000毫秒",
                "waitTime":3000},
{
                "action":"setPanelState",
                "description":"设置 图片 到 Next 淡入淡出 out 500ms 淡入淡出 in 500ms 自动循环 循环间隔 3000 毫秒",
                "panelsToStates":[{
                    "panelPath":["6a642d33baeb45008e1975b27ccf2a18"],
                    "stateInfo":{
                      "setStateType":"next",
                      "stateNumber":1,
                      "stateValue":{
                        "exprType":"stringLiteral",
                        "value":"1",
                        "stos":[]},
                      "loop":true,
                      "showWhenSet":false,
                      "repeat":3000,
                      "options":{
                        "animateOut":{
                          "easing":"fade",
                          "duration":500},
                        "animateIn":{
                          "easing":"fade",
                          "duration":500},
                        "compress":false}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"6a642d33baeb45008e1975b27ccf2a18",
          "label":"图片",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":47,
              "y":12},
            "size":{
              "width":240,
              "height":142}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"53c552bb00f84651ac972c536cb9d284",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"920f402f884c4596b19321268a9514bd",
                  "label":"",
                  "parentDynamicPanel":"6a642d33baeb45008e1975b27ccf2a18",
                  "panelIndex":0,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":240,
                      "height":142}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ddceca0b8334e40a4ff94b1686fda49",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6a642d33baeb45008e1975b27ccf2a18",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":240,
                          "height":142}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u1.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"16e22c8978fa4be0b21d2c17a970b3f0",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"25b61c67399448f08593a4af46b1fc43",
                  "label":"",
                  "parentDynamicPanel":"6a642d33baeb45008e1975b27ccf2a18",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":240,
                      "height":142}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6d5a48e1cca04aceaac85dba3828e6e1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6a642d33baeb45008e1975b27ccf2a18",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":240,
                          "height":142}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u3.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"63e8808b39b349868bf5307eaadcc7e6",
              "label":"状态3",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3a086ae4307a45cc84cbb4276c84cc12",
                  "label":"",
                  "parentDynamicPanel":"6a642d33baeb45008e1975b27ccf2a18",
                  "panelIndex":2,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":240,
                      "height":142}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"20a78474be4147dbabdd28ac00d78587",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"6a642d33baeb45008e1975b27ccf2a18",
                      "panelIndex":2,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":240,
                          "height":142}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u5.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"c90fadb1e5bf406aa6f03de20904de6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":309,
              "y":62},
            "size":{
              "width":10,
              "height":30},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ae66df21d4e466aa0223c5d8ebc0b59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":309,
                  "y":62},
                "size":{
                  "width":10,
                  "height":30},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 图片 到 Next 淡入淡出 out 500ms 淡入淡出 in 500ms 显示隐藏 自动循环",
                      "panelsToStates":[{
                          "panelPath":["6a642d33baeb45008e1975b27ccf2a18"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":true,
                            "options":{
                              "animateOut":{
                                "easing":"fade",
                                "duration":500},
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u7.png"}},
{
          "id":"449d4d7557644a378ed5c4275a67a8bb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":13,
              "y":62},
            "size":{
              "width":10,
              "height":30},
            "borderWidth":"-1",
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c561b8ef23d4470aaeed585d9fe76006",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":13,
                  "y":62},
                "size":{
                  "width":10,
                  "height":30},
                "borderWidth":"-1",
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 图片 到 Previous 淡入淡出 out 500ms 淡入淡出 in 500ms 显示隐藏 自动循环",
                      "panelsToStates":[{
                          "panelPath":["6a642d33baeb45008e1975b27ccf2a18"],
                          "stateInfo":{
                            "setStateType":"previous",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":true,
                            "options":{
                              "animateOut":{
                                "easing":"fade",
                                "duration":500},
                              "animateIn":{
                                "easing":"fade",
                                "duration":500},
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u9.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "6a642d33baeb45008e1975b27ccf2a18":{
      "scriptId":"u0"},
    "920f402f884c4596b19321268a9514bd":{
      "scriptId":"u1"},
    "2ddceca0b8334e40a4ff94b1686fda49":{
      "scriptId":"u2"},
    "25b61c67399448f08593a4af46b1fc43":{
      "scriptId":"u3"},
    "6d5a48e1cca04aceaac85dba3828e6e1":{
      "scriptId":"u4"},
    "3a086ae4307a45cc84cbb4276c84cc12":{
      "scriptId":"u5"},
    "20a78474be4147dbabdd28ac00d78587":{
      "scriptId":"u6"},
    "c90fadb1e5bf406aa6f03de20904de6a":{
      "scriptId":"u7"},
    "3ae66df21d4e466aa0223c5d8ebc0b59":{
      "scriptId":"u8"},
    "449d4d7557644a378ed5c4275a67a8bb":{
      "scriptId":"u9"},
    "c561b8ef23d4470aaeed585d9fe76006":{
      "scriptId":"u10"}}});