$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1442459498894.19),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a40e01fdfd8744f0bd3a67717cad50a9",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d49a086f4a9c4270aae39ba3463b9a69",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":310,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"539bad29fe694699b2d4a543a594d2c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":310,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"d5f0ef0202624def9c4a55c628d26ac2",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":166,
              "y":91},
            "size":{
              "width":80,
              "height":22}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSelectionChange":{
              "description":"OnSelectionChange",
              "cases":[{
                  "description":"用例 1<br> (If 选中项值 当前部件 = &quot;201505&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"201505",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /docs/docs/DocDsp.jsp?id=271",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/docs/docs/DocDsp.jsp?id=271",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]},
{
                  "description":"用例 2<br> (Else If 选中项值 当前部件 = &quot;201504&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"201504",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /docs/docs/DocDsp.jsp?id=272",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/docs/docs/DocDsp.jsp?id=272",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]},
{
                  "description":"用例 3<br> (Else If 选中项值 当前部件 = &quot;201503&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"201503",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /docs/docs/DocDsp.jsp?id=273",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/docs/docs/DocDsp.jsp?id=273",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]},
{
                  "description":"用例 4<br> (Else If 选中项值 当前部件 = &quot;201502&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"==",
                    "leftExpr":{
                      "exprType":"fcall",
                      "functionName":"GetSelectedOption",
                      "arguments":[{
                          "exprType":"pathLiteral",
                          "isThis":true,
                          "isFocused":false,
                          "isTarget":false}]},
                    "rightExpr":{
                      "exprType":"stringLiteral",
                      "value":"201502",
                      "stos":[]}},
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /docs/docs/DocDsp.jsp?id=274",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/docs/docs/DocDsp.jsp?id=274",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}}}]}},
  "masters":{
},
  "objectPaths":{
    "d49a086f4a9c4270aae39ba3463b9a69":{
      "scriptId":"u0"},
    "539bad29fe694699b2d4a543a594d2c9":{
      "scriptId":"u1"},
    "d5f0ef0202624def9c4a55c628d26ac2":{
      "scriptId":"u2"}}});