$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1441787985015.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"33df6838e5704d15a2da6d0993a042f3",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fcdd5b796d994648b2795c3e4cb0a255",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":4,
              "y":20},
            "size":{
              "width":85,
              "height":82}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbc3c26955064a058c55fa1672d6af14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":4,
                  "y":20},
                "size":{
                  "width":85,
                  "height":82}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"5aae387e54604bc0ad633c439076f036",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":100,
              "y":10},
            "size":{
              "width":310,
              "height":31},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93340416121d4ac99ffd05e5fbad549c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":100,
                  "y":10},
                "size":{
                  "width":310,
                  "height":31},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png",
            "mouseOver~":"images/home/u2.png"}},
{
          "id":"3bb0726e8c884c6e95d494fba6754a4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":100,
              "y":50},
            "size":{
              "width":310,
              "height":31},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"663d78bc86c8462ca012ad024c6a8e43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":100,
                  "y":50},
                "size":{
                  "width":310,
                  "height":31},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png",
            "mouseOver~":"images/home/u2.png"}},
{
          "id":"ccdd5d20d60d47d2aaf05d40d3249bbe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"16px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6B6B6B,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":100,
              "y":90},
            "size":{
              "width":310,
              "height":31},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87af88a93c9b490d86fac35d7277623b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6B6B6B,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":100,
                  "y":90},
                "size":{
                  "width":310,
                  "height":31},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png",
            "mouseOver~":"images/home/u2.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "fcdd5b796d994648b2795c3e4cb0a255":{
      "scriptId":"u0"},
    "fbc3c26955064a058c55fa1672d6af14":{
      "scriptId":"u1"},
    "5aae387e54604bc0ad633c439076f036":{
      "scriptId":"u2"},
    "93340416121d4ac99ffd05e5fbad549c":{
      "scriptId":"u3"},
    "3bb0726e8c884c6e95d494fba6754a4f":{
      "scriptId":"u4"},
    "663d78bc86c8462ca012ad024c6a8e43":{
      "scriptId":"u5"},
    "ccdd5d20d60d47d2aaf05d40d3249bbe":{
      "scriptId":"u6"},
    "87af88a93c9b490d86fac35d7277623b":{
      "scriptId":"u7"}}});