$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1441902303465.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0a0ad40d907243b982fae0544de9e8db",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a65a8671360241478caac66884d51538",
          "label":"交流反馈",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4979AE,
              "opacity":1},
            "stateStyles":{
              "mouseDown":{
},
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4979AE}}},
            "location":{
              "x":100,
              "y":0},
            "size":{
              "width":100,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e7f596388b94843b734fa6814551c80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4979AE,
                  "opacity":1},
                "stateStyles":{
                  "mouseDown":{
},
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF4979AE}}},
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 交流反馈 = &quot;true&quot;, 且<br> 选中状态值 项目日报 = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a65a8671360241478caac66884d51538"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["27198c2a7f2840c4a6acc480a11a059c"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}},
{
                      "action":"setPanelState",
                      "description":"设置 内容显示 到 交流反馈",
                      "panelsToStates":[{
                          "panelPath":["5fa212189bb44cdd83b11f08175267a5"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/交流反馈_u0.png",
            "selected~":"images/home/交流反馈_u0_selected.png"}},
{
          "id":"5fa212189bb44cdd83b11f08175267a5",
          "label":"内容显示",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":600,
              "height":170}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onLoad":{
              "description":"OnLoad",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"移动 滚动循环1 相对位置为 (0,-170) 缓慢进入退出 2000ms",
                      "objectsToMoves":[{
                          "objectPath":["cc83d84b7aeb48469cf6f71bbc0a2b3e"],
                          "moveInfo":{
                            "moveType":"delta",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"-170",
                              "stos":[]},
                            "options":{
                              "easing":"easeInOutCubic",
                              "duration":2000}}}]},
{
                      "action":"wait",
                      "description":"等待4000毫秒",
                      "waitTime":4000},
{
                      "action":"moveWidget",
                      "description":"移动 滚动循环1 相对位置为 (0,-170) 缓慢进入退出 2000ms",
                      "objectsToMoves":[{
                          "objectPath":["cc83d84b7aeb48469cf6f71bbc0a2b3e"],
                          "moveInfo":{
                            "moveType":"delta",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"-170",
                              "stos":[]},
                            "options":{
                              "easing":"easeInOutCubic",
                              "duration":2000}}}]},
{
                      "action":"wait",
                      "description":"等待4000毫秒",
                      "waitTime":4000},
{
                      "action":"moveWidget",
                      "description":"移动 滚动循环1 相对位置为 (0,-170) 缓慢进入退出 2000ms",
                      "objectsToMoves":[{
                          "objectPath":["cc83d84b7aeb48469cf6f71bbc0a2b3e"],
                          "moveInfo":{
                            "moveType":"delta",
                            "xValue":{
                              "exprType":"stringLiteral",
                              "value":"0",
                              "stos":[]},
                            "yValue":{
                              "exprType":"stringLiteral",
                              "value":"-170",
                              "stos":[]},
                            "options":{
                              "easing":"easeInOutCubic",
                              "duration":2000}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 滚动循环2",
                      "objectsToFades":[{
                          "objectPath":["56cf90579c1845f68c4a98df25c77c01"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"隐藏 滚动循环1",
                      "objectsToFades":[{
                          "objectPath":["cc83d84b7aeb48469cf6f71bbc0a2b3e"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "percentWidth":1,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"eef5958955cc43d6a949f1a22df15d32",
              "label":"项目日报",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e27e24a2638d433d8a4dea9ffef0666c",
                  "label":"项目日报",
                  "parentDynamicPanel":"5fa212189bb44cdd83b11f08175267a5",
                  "panelIndex":0,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "verticalAlignment":"top",
                    "size":{
                      "width":600,
                      "height":510},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"99c876af114b49a3a5860ebd3d0a092f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5fa212189bb44cdd83b11f08175267a5",
                      "panelIndex":0,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "verticalAlignment":"top",
                        "size":{
                          "width":600,
                          "height":510},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/项目日报_u3.png"}},
{
                  "id":"cc83d84b7aeb48469cf6f71bbc0a2b3e",
                  "label":"滚动循环1",
                  "parentDynamicPanel":"5fa212189bb44cdd83b11f08175267a5",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":600,
                      "height":510}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onShow":{
                      "description":"OnShow",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"移动 滚动循环1 到 (0,170)",
                              "objectsToMoves":[{
                                  "objectPath":["cc83d84b7aeb48469cf6f71bbc0a2b3e"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"170",
                                      "stos":[]},
                                    "options":{
}}}]},
{
                              "action":"moveWidget",
                              "description":"移动 滚动循环1 相对位置为 (0,-170) 缓慢进入退出 2000ms",
                              "objectsToMoves":[{
                                  "objectPath":["cc83d84b7aeb48469cf6f71bbc0a2b3e"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-170",
                                      "stos":[]},
                                    "options":{
                                      "easing":"easeInOutCubic",
                                      "duration":2000}}}]},
{
                              "action":"wait",
                              "description":"等待4000毫秒",
                              "waitTime":4000},
{
                              "action":"moveWidget",
                              "description":"移动 滚动循环1 相对位置为 (0,-170) 缓慢进入退出 2000ms",
                              "objectsToMoves":[{
                                  "objectPath":["cc83d84b7aeb48469cf6f71bbc0a2b3e"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-170",
                                      "stos":[]},
                                    "options":{
                                      "easing":"easeInOutCubic",
                                      "duration":2000}}}]},
{
                              "action":"wait",
                              "description":"等待4000毫秒",
                              "waitTime":4000},
{
                              "action":"moveWidget",
                              "description":"移动 滚动循环1 相对位置为 (0,-170) 缓慢进入退出 2000ms",
                              "objectsToMoves":[{
                                  "objectPath":["cc83d84b7aeb48469cf6f71bbc0a2b3e"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-170",
                                      "stos":[]},
                                    "options":{
                                      "easing":"easeInOutCubic",
                                      "duration":2000}}}]},
{
                              "action":"wait",
                              "description":"等待4000毫秒",
                              "waitTime":4000},
{
                              "action":"moveWidget",
                              "description":"移动 滚动循环1 相对位置为 (0,-170) 缓慢进入退出 2000ms",
                              "objectsToMoves":[{
                                  "objectPath":["cc83d84b7aeb48469cf6f71bbc0a2b3e"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-170",
                                      "stos":[]},
                                    "options":{
                                      "easing":"easeInOutCubic",
                                      "duration":2000}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示 滚动循环2",
                              "objectsToFades":[{
                                  "objectPath":["56cf90579c1845f68c4a98df25c77c01"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 滚动循环1",
                              "objectsToFades":[{
                                  "objectPath":["cc83d84b7aeb48469cf6f71bbc0a2b3e"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"ea7b6977a28e41ae8c1d5ca8433d22f1",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"6e6bd621432e47fbb99b6f5ccacd6754",
                          "label":"日报1-1",
                          "parentDynamicPanel":"cc83d84b7aeb48469cf6f71bbc0a2b3e",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"left",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF6F6F6},
                            "size":{
                              "width":600,
                              "height":40},
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFF6F6F6}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"439b2b36c28548119e365cb372be327f",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"cc83d84b7aeb48469cf6f71bbc0a2b3e",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"left",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFF6F6F6},
                                "size":{
                                  "width":600,
                                  "height":40},
                                "borderWidth":"-1",
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFF6F6F6}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/日报1-1_u6.png"}},
{
                          "id":"b62fc27d64bb430d9ba328fa290912e9",
                          "label":"日报1-2",
                          "parentDynamicPanel":"cc83d84b7aeb48469cf6f71bbc0a2b3e",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Bold', '微软雅黑'",
                            "horizontalAlignment":"left",
                            "verticalAlignment":"top",
                            "location":{
                              "x":0,
                              "y":40},
                            "size":{
                              "width":600,
                              "height":130},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"46aa2d3161d94124b8adb6a4be07e593",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"cc83d84b7aeb48469cf6f71bbc0a2b3e",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                                "horizontalAlignment":"left",
                                "verticalAlignment":"top",
                                "location":{
                                  "x":0,
                                  "y":40},
                                "size":{
                                  "width":600,
                                  "height":130},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/日报1-2_u8.png"}},
{
                          "id":"7814e74863ea48ce87d7e37fffce214e",
                          "label":"日报2-1",
                          "parentDynamicPanel":"cc83d84b7aeb48469cf6f71bbc0a2b3e",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"left",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF6F6F6},
                            "location":{
                              "x":0,
                              "y":170},
                            "size":{
                              "width":600,
                              "height":40},
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFF6F6F6}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f2e467eca5354beeac10ef136d7d97e3",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"cc83d84b7aeb48469cf6f71bbc0a2b3e",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"left",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFF6F6F6},
                                "location":{
                                  "x":0,
                                  "y":170},
                                "size":{
                                  "width":600,
                                  "height":40},
                                "borderWidth":"-1",
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFF6F6F6}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/日报1-1_u6.png"}},
{
                          "id":"c3a716024cf64afd923ffe69981f8b9e",
                          "label":"日报2-2",
                          "parentDynamicPanel":"cc83d84b7aeb48469cf6f71bbc0a2b3e",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Bold', '微软雅黑'",
                            "horizontalAlignment":"left",
                            "verticalAlignment":"top",
                            "location":{
                              "x":0,
                              "y":210},
                            "size":{
                              "width":600,
                              "height":130},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"6820bf4f143142d7bfe55b7416fe9120",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"cc83d84b7aeb48469cf6f71bbc0a2b3e",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                                "horizontalAlignment":"left",
                                "verticalAlignment":"top",
                                "location":{
                                  "x":0,
                                  "y":210},
                                "size":{
                                  "width":600,
                                  "height":130},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/日报1-2_u8.png"}},
{
                          "id":"f9f4392da64348b0be6b5db8d3f5d54a",
                          "label":"日报3-1",
                          "parentDynamicPanel":"cc83d84b7aeb48469cf6f71bbc0a2b3e",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"left",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF6F6F6},
                            "location":{
                              "x":0,
                              "y":340},
                            "size":{
                              "width":600,
                              "height":40},
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFF6F6F6}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"8d66b542b92044a683c39caa1012c4e1",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"cc83d84b7aeb48469cf6f71bbc0a2b3e",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"left",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFF6F6F6},
                                "location":{
                                  "x":0,
                                  "y":340},
                                "size":{
                                  "width":600,
                                  "height":40},
                                "borderWidth":"-1",
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFF6F6F6}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/日报1-1_u6.png"}},
{
                          "id":"8133ed34e48b47ffaa92a5f282a95564",
                          "label":"日报3-2",
                          "parentDynamicPanel":"cc83d84b7aeb48469cf6f71bbc0a2b3e",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Bold', '微软雅黑'",
                            "horizontalAlignment":"left",
                            "verticalAlignment":"top",
                            "location":{
                              "x":0,
                              "y":380},
                            "size":{
                              "width":600,
                              "height":130},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"a4457fa54c384f1d8ec813dbc5bb5fa4",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"cc83d84b7aeb48469cf6f71bbc0a2b3e",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                                "horizontalAlignment":"left",
                                "verticalAlignment":"top",
                                "location":{
                                  "x":0,
                                  "y":380},
                                "size":{
                                  "width":600,
                                  "height":130},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/日报1-2_u8.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]},
{
                  "id":"56cf90579c1845f68c4a98df25c77c01",
                  "label":"滚动循环2",
                  "parentDynamicPanel":"5fa212189bb44cdd83b11f08175267a5",
                  "panelIndex":0,
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":false,
                  "style":{
                    "size":{
                      "width":600,
                      "height":510},
                    "visible":false},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onShow":{
                      "description":"OnShow",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"moveWidget",
                              "description":"移动 滚动循环2 到 (0,170)",
                              "objectsToMoves":[{
                                  "objectPath":["56cf90579c1845f68c4a98df25c77c01"],
                                  "moveInfo":{
                                    "moveType":"location",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"170",
                                      "stos":[]},
                                    "options":{
}}}]},
{
                              "action":"moveWidget",
                              "description":"移动 滚动循环2 相对位置为 (0,-170) 缓慢进入退出 2000ms",
                              "objectsToMoves":[{
                                  "objectPath":["56cf90579c1845f68c4a98df25c77c01"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-170",
                                      "stos":[]},
                                    "options":{
                                      "easing":"easeInOutCubic",
                                      "duration":2000}}}]},
{
                              "action":"wait",
                              "description":"等待4000毫秒",
                              "waitTime":4000},
{
                              "action":"moveWidget",
                              "description":"移动 滚动循环2 相对位置为 (0,-170) 缓慢进入退出 2000ms",
                              "objectsToMoves":[{
                                  "objectPath":["56cf90579c1845f68c4a98df25c77c01"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-170",
                                      "stos":[]},
                                    "options":{
                                      "easing":"easeInOutCubic",
                                      "duration":2000}}}]},
{
                              "action":"wait",
                              "description":"等待4000毫秒",
                              "waitTime":4000},
{
                              "action":"moveWidget",
                              "description":"移动 滚动循环2 相对位置为 (0,-170) 缓慢进入退出 2000ms",
                              "objectsToMoves":[{
                                  "objectPath":["56cf90579c1845f68c4a98df25c77c01"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-170",
                                      "stos":[]},
                                    "options":{
                                      "easing":"easeInOutCubic",
                                      "duration":2000}}}]},
{
                              "action":"wait",
                              "description":"等待4000毫秒",
                              "waitTime":4000},
{
                              "action":"moveWidget",
                              "description":"移动 滚动循环2 相对位置为 (0,-170) 缓慢进入退出 2000ms",
                              "objectsToMoves":[{
                                  "objectPath":["56cf90579c1845f68c4a98df25c77c01"],
                                  "moveInfo":{
                                    "moveType":"delta",
                                    "xValue":{
                                      "exprType":"stringLiteral",
                                      "value":"0",
                                      "stos":[]},
                                    "yValue":{
                                      "exprType":"stringLiteral",
                                      "value":"-170",
                                      "stos":[]},
                                    "options":{
                                      "easing":"easeInOutCubic",
                                      "duration":2000}}}]},
{
                              "action":"fadeWidget",
                              "description":"显示 滚动循环1",
                              "objectsToFades":[{
                                  "objectPath":["cc83d84b7aeb48469cf6f71bbc0a2b3e"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 滚动循环2",
                              "objectsToFades":[{
                                  "objectPath":["56cf90579c1845f68c4a98df25c77c01"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "scrollbars":"none",
                  "fitToContent":true,
                  "propagate":false,
                  "diagrams":[{
                      "id":"6432d887e90945f49df8e7c8334f7b8e",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"02817d86731f4e598404b4cff7e0b000",
                          "label":"日报1-1",
                          "parentDynamicPanel":"56cf90579c1845f68c4a98df25c77c01",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"left",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF6F6F6},
                            "size":{
                              "width":600,
                              "height":40},
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFF6F6F6}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"8d93552b7d3e41a58f3679bb6ae3e5e6",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"56cf90579c1845f68c4a98df25c77c01",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"left",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFF6F6F6},
                                "size":{
                                  "width":600,
                                  "height":40},
                                "borderWidth":"-1",
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFF6F6F6}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/日报1-1_u6.png"}},
{
                          "id":"7859489afe954c56ab74c22d01581f8e",
                          "label":"日报1-2",
                          "parentDynamicPanel":"56cf90579c1845f68c4a98df25c77c01",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Bold', '微软雅黑'",
                            "horizontalAlignment":"left",
                            "verticalAlignment":"top",
                            "location":{
                              "x":0,
                              "y":40},
                            "size":{
                              "width":600,
                              "height":130},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"d382cd60dd314456a742450a59a269a6",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"56cf90579c1845f68c4a98df25c77c01",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                                "horizontalAlignment":"left",
                                "verticalAlignment":"top",
                                "location":{
                                  "x":0,
                                  "y":40},
                                "size":{
                                  "width":600,
                                  "height":130},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/日报1-2_u8.png"}},
{
                          "id":"bb9911710fbc4b89b9815b215e7feddc",
                          "label":"日报2-1",
                          "parentDynamicPanel":"56cf90579c1845f68c4a98df25c77c01",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"left",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF6F6F6},
                            "location":{
                              "x":0,
                              "y":170},
                            "size":{
                              "width":600,
                              "height":40},
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFF6F6F6}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"5cc66cdd74424d88b10d88a6433cf95b",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"56cf90579c1845f68c4a98df25c77c01",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"left",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFF6F6F6},
                                "location":{
                                  "x":0,
                                  "y":170},
                                "size":{
                                  "width":600,
                                  "height":40},
                                "borderWidth":"-1",
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFF6F6F6}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/日报1-1_u6.png"}},
{
                          "id":"95548add622c4732918656f68041ebf3",
                          "label":"日报2-2",
                          "parentDynamicPanel":"56cf90579c1845f68c4a98df25c77c01",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Bold', '微软雅黑'",
                            "horizontalAlignment":"left",
                            "verticalAlignment":"top",
                            "location":{
                              "x":0,
                              "y":210},
                            "size":{
                              "width":600,
                              "height":130},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"238fb625ccb1481fa4a70e6d6d41b709",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"56cf90579c1845f68c4a98df25c77c01",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                                "horizontalAlignment":"left",
                                "verticalAlignment":"top",
                                "location":{
                                  "x":0,
                                  "y":210},
                                "size":{
                                  "width":600,
                                  "height":130},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/日报1-2_u8.png"}},
{
                          "id":"cd4f1dd9d38744828c3f994e57d4bdf7",
                          "label":"日报3-1",
                          "parentDynamicPanel":"56cf90579c1845f68c4a98df25c77c01",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "horizontalAlignment":"left",
                            "fill":{
                              "fillType":"solid",
                              "color":0xFFF6F6F6},
                            "location":{
                              "x":0,
                              "y":340},
                            "size":{
                              "width":600,
                              "height":40},
                            "borderWidth":"-1",
                            "borderFill":{
                              "fillType":"solid",
                              "color":0xFFF6F6F6}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"de17d70a6bf446079243bacc6b21ccef",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"56cf90579c1845f68c4a98df25c77c01",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "horizontalAlignment":"left",
                                "fill":{
                                  "fillType":"solid",
                                  "color":0xFFF6F6F6},
                                "location":{
                                  "x":0,
                                  "y":340},
                                "size":{
                                  "width":600,
                                  "height":40},
                                "borderWidth":"-1",
                                "borderFill":{
                                  "fillType":"solid",
                                  "color":0xFFF6F6F6}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/日报1-1_u6.png"}},
{
                          "id":"fab1afa87c58417d8a464acffc7cd878",
                          "label":"日报3-2",
                          "parentDynamicPanel":"56cf90579c1845f68c4a98df25c77c01",
                          "panelIndex":0,
                          "type":"buttonShape",
                          "styleType":"buttonShape",
                          "visible":true,
                          "style":{
                            "fontName":"'微软雅黑 Bold', '微软雅黑'",
                            "horizontalAlignment":"left",
                            "verticalAlignment":"top",
                            "location":{
                              "x":0,
                              "y":380},
                            "size":{
                              "width":600,
                              "height":130},
                            "borderWidth":"-1"},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"1e58fcd9aaac494b97ae5a0e5bdb7cf0",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"56cf90579c1845f68c4a98df25c77c01",
                              "panelIndex":0,
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                                "horizontalAlignment":"left",
                                "verticalAlignment":"top",
                                "location":{
                                  "x":0,
                                  "y":380},
                                "size":{
                                  "width":600,
                                  "height":130},
                                "borderWidth":"-1"},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/home/日报1-2_u8.png"}}],
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFFFFF},
                        "image":null,
                        "imageHorizontalAlignment":"near",
                        "imageVerticalAlignment":"near",
                        "imageRepeat":"auto"},
                      "adaptiveStyles":{
}}]}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}},
{
              "id":"ff87e57acd2f423e9d09fd3ad9f635a8",
              "label":"交流反馈",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f1e4ed8df7d04bcc91aef63c1eeebf2c",
                  "label":"交流反馈",
                  "parentDynamicPanel":"5fa212189bb44cdd83b11f08175267a5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"left",
                    "verticalAlignment":"top",
                    "size":{
                      "width":600,
                      "height":170},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8ed0c05ff75a401383ba8c018b9ede0e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5fa212189bb44cdd83b11f08175267a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "horizontalAlignment":"left",
                        "verticalAlignment":"top",
                        "size":{
                          "width":600,
                          "height":170},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/交流反馈_u31.png"}},
{
                  "id":"82285f8e5c9b429cb17e52fd0b47682d",
                  "label":"",
                  "parentDynamicPanel":"5fa212189bb44cdd83b11f08175267a5",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":10},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"57039e5597064fdba0d827b7c89717d1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5fa212189bb44cdd83b11f08175267a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":10},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u33.jpg"}},
{
                  "id":"62189f48bae44e9bae1c67c8c9022e92",
                  "label":"",
                  "parentDynamicPanel":"5fa212189bb44cdd83b11f08175267a5",
                  "panelIndex":1,
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":80},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3903e52f3d2243b98c6490412d912763",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5fa212189bb44cdd83b11f08175267a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":80},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u35.jpg"}},
{
                  "id":"5cf3eb8be3124335b05454a1718e7028",
                  "label":"",
                  "parentDynamicPanel":"5fa212189bb44cdd83b11f08175267a5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF868686,
                      "opacity":1},
                    "location":{
                      "x":100,
                      "y":29},
                    "size":{
                      "width":460,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b15dc4f9b7924e0f80d228b7e46dc591",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5fa212189bb44cdd83b11f08175267a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF868686,
                          "opacity":1},
                        "location":{
                          "x":100,
                          "y":29},
                        "size":{
                          "width":460,
                          "height":30},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u37.png"}},
{
                  "id":"93dcbcc29ffd4cefa8b8b7c76a1dbf20",
                  "label":"",
                  "parentDynamicPanel":"5fa212189bb44cdd83b11f08175267a5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1},
                    "location":{
                      "x":100,
                      "y":8},
                    "size":{
                      "width":460,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"48f4ec823cab46bba26a7018bd75a4f8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5fa212189bb44cdd83b11f08175267a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"12px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0033FF,
                          "opacity":1},
                        "location":{
                          "x":100,
                          "y":8},
                        "size":{
                          "width":460,
                          "height":30},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u37.png"}},
{
                  "id":"8cb6ed12abb94532a45b267ad779d739",
                  "label":"",
                  "parentDynamicPanel":"5fa212189bb44cdd83b11f08175267a5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF868686,
                      "opacity":1},
                    "location":{
                      "x":100,
                      "y":100},
                    "size":{
                      "width":460,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7c124fb0180547b9a2080b1e53dd5928",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5fa212189bb44cdd83b11f08175267a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF868686,
                          "opacity":1},
                        "location":{
                          "x":100,
                          "y":100},
                        "size":{
                          "width":460,
                          "height":30},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u37.png"}},
{
                  "id":"fa5215e1739146f782aa0a2f981481aa",
                  "label":"",
                  "parentDynamicPanel":"5fa212189bb44cdd83b11f08175267a5",
                  "panelIndex":1,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"12px",
                    "horizontalAlignment":"left",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1},
                    "location":{
                      "x":100,
                      "y":79},
                    "size":{
                      "width":460,
                      "height":30},
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"59b8d35260b6432ea600bfe2085bd9c0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"5fa212189bb44cdd83b11f08175267a5",
                      "panelIndex":1,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"12px",
                        "horizontalAlignment":"left",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF0033FF,
                          "opacity":1},
                        "location":{
                          "x":100,
                          "y":79},
                        "size":{
                          "width":460,
                          "height":30},
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u37.png"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
}}]},
{
          "id":"27198c2a7f2840c4a6acc480a11a059c",
          "label":"项目日报",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "selected":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4979AE,
              "opacity":1},
            "stateStyles":{
              "selected":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4979AE}}},
            "size":{
              "width":100,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"814d761be03542738b899f93b283e1e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4979AE,
                  "opacity":1},
                "stateStyles":{
                  "selected":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF4979AE}}},
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 交流反馈 = &quot;false&quot;, 且<br> 选中状态值 项目日报 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["a65a8671360241478caac66884d51538"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["27198c2a7f2840c4a6acc480a11a059c"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}},
{
                      "action":"setPanelState",
                      "description":"设置 内容显示 到 项目日报",
                      "panelsToStates":[{
                          "panelPath":["5fa212189bb44cdd83b11f08175267a5"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/交流反馈_u0.png",
            "selected~":"images/home/交流反馈_u0_selected.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a65a8671360241478caac66884d51538":{
      "scriptId":"u0"},
    "5e7f596388b94843b734fa6814551c80":{
      "scriptId":"u1"},
    "5fa212189bb44cdd83b11f08175267a5":{
      "scriptId":"u2"},
    "e27e24a2638d433d8a4dea9ffef0666c":{
      "scriptId":"u3"},
    "99c876af114b49a3a5860ebd3d0a092f":{
      "scriptId":"u4"},
    "cc83d84b7aeb48469cf6f71bbc0a2b3e":{
      "scriptId":"u5"},
    "6e6bd621432e47fbb99b6f5ccacd6754":{
      "scriptId":"u6"},
    "439b2b36c28548119e365cb372be327f":{
      "scriptId":"u7"},
    "b62fc27d64bb430d9ba328fa290912e9":{
      "scriptId":"u8"},
    "46aa2d3161d94124b8adb6a4be07e593":{
      "scriptId":"u9"},
    "7814e74863ea48ce87d7e37fffce214e":{
      "scriptId":"u10"},
    "f2e467eca5354beeac10ef136d7d97e3":{
      "scriptId":"u11"},
    "c3a716024cf64afd923ffe69981f8b9e":{
      "scriptId":"u12"},
    "6820bf4f143142d7bfe55b7416fe9120":{
      "scriptId":"u13"},
    "f9f4392da64348b0be6b5db8d3f5d54a":{
      "scriptId":"u14"},
    "8d66b542b92044a683c39caa1012c4e1":{
      "scriptId":"u15"},
    "8133ed34e48b47ffaa92a5f282a95564":{
      "scriptId":"u16"},
    "a4457fa54c384f1d8ec813dbc5bb5fa4":{
      "scriptId":"u17"},
    "56cf90579c1845f68c4a98df25c77c01":{
      "scriptId":"u18"},
    "02817d86731f4e598404b4cff7e0b000":{
      "scriptId":"u19"},
    "8d93552b7d3e41a58f3679bb6ae3e5e6":{
      "scriptId":"u20"},
    "7859489afe954c56ab74c22d01581f8e":{
      "scriptId":"u21"},
    "d382cd60dd314456a742450a59a269a6":{
      "scriptId":"u22"},
    "bb9911710fbc4b89b9815b215e7feddc":{
      "scriptId":"u23"},
    "5cc66cdd74424d88b10d88a6433cf95b":{
      "scriptId":"u24"},
    "95548add622c4732918656f68041ebf3":{
      "scriptId":"u25"},
    "238fb625ccb1481fa4a70e6d6d41b709":{
      "scriptId":"u26"},
    "cd4f1dd9d38744828c3f994e57d4bdf7":{
      "scriptId":"u27"},
    "de17d70a6bf446079243bacc6b21ccef":{
      "scriptId":"u28"},
    "fab1afa87c58417d8a464acffc7cd878":{
      "scriptId":"u29"},
    "1e58fcd9aaac494b97ae5a0e5bdb7cf0":{
      "scriptId":"u30"},
    "f1e4ed8df7d04bcc91aef63c1eeebf2c":{
      "scriptId":"u31"},
    "8ed0c05ff75a401383ba8c018b9ede0e":{
      "scriptId":"u32"},
    "82285f8e5c9b429cb17e52fd0b47682d":{
      "scriptId":"u33"},
    "57039e5597064fdba0d827b7c89717d1":{
      "scriptId":"u34"},
    "62189f48bae44e9bae1c67c8c9022e92":{
      "scriptId":"u35"},
    "3903e52f3d2243b98c6490412d912763":{
      "scriptId":"u36"},
    "5cf3eb8be3124335b05454a1718e7028":{
      "scriptId":"u37"},
    "b15dc4f9b7924e0f80d228b7e46dc591":{
      "scriptId":"u38"},
    "93dcbcc29ffd4cefa8b8b7c76a1dbf20":{
      "scriptId":"u39"},
    "48f4ec823cab46bba26a7018bd75a4f8":{
      "scriptId":"u40"},
    "8cb6ed12abb94532a45b267ad779d739":{
      "scriptId":"u41"},
    "7c124fb0180547b9a2080b1e53dd5928":{
      "scriptId":"u42"},
    "fa5215e1739146f782aa0a2f981481aa":{
      "scriptId":"u43"},
    "59b8d35260b6432ea600bfe2085bd9c0":{
      "scriptId":"u44"},
    "27198c2a7f2840c4a6acc480a11a059c":{
      "scriptId":"u45"},
    "814d761be03542738b899f93b283e1e4":{
      "scriptId":"u46"}}});