$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1441792602415.05),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"68c5c52b247f436092de540cd0c04bb9",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ac72372f77d64944ad54f0cbe33683e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0x82F2F2F2},
            "size":{
              "width":400,
              "height":340},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da0593c908cc4976b332a1ef755152f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0x82F2F2F2},
                "size":{
                  "width":400,
                  "height":340},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"9e730c1009484f7ba53b02cac02c5226",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "fill":{
              "fillType":"solid",
              "color":0xFFE0ECFA},
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":380,
              "height":30},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a98a9e4948c1445fb39b22e61b10cf95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE0ECFA},
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":380,
                  "height":30},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"b70ee0cb89004b15b90d198d3ab0ae6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA69A9B,
              "opacity":1},
            "location":{
              "x":10,
              "y":40},
            "size":{
              "width":380,
              "height":90},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc3fe654a73548bca10ad2b3aec507f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA69A9B,
                  "opacity":1},
                "location":{
                  "x":10,
                  "y":40},
                "size":{
                  "width":380,
                  "height":90},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"89fbb1dd4edd41ee88f4e147540c5433",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":140},
            "size":{
              "width":380,
              "height":90},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f83754b1163b4d64809b722ec04338e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":140},
                "size":{
                  "width":380,
                  "height":90},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"42faf4bb33c74fc8bfc46d66dc85c863",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":240},
            "size":{
              "width":380,
              "height":90},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af1d16d4dd234f2d8465be11842cc7df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":240},
                "size":{
                  "width":380,
                  "height":90},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"cdd807ff07f5483db2f27756828cc28b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":25,
              "y":45},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e416caebb424106ad706356313435d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":25,
                  "y":45},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /docs/docs/DocDsp.jsp?id=125&amp;isOpenFirstAss=0&amp;e71441596592544=",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/docs/docs/DocDsp.jsp?id=125&isOpenFirstAss=0&e71441596592544=",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u10.png"}},
{
          "id":"c80a1029fc054140a452cdf946f1fd16",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":145},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f22e5d0c79aa439b82992836dfaf2eb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":145},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /docs/docs/DocDsp.jsp?id=135&amp;isOpenFirstAss=0&amp;e71441596676478=",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/docs/docs/DocDsp.jsp?id=135&isOpenFirstAss=0&e71441596676478=",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u12.png"}},
{
          "id":"20f52041e7a84e0fade7a2231893fcb9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":25,
              "y":245},
            "size":{
              "width":50,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a7963aeced8479cb53c13a179f7a19d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":25,
                  "y":245},
                "size":{
                  "width":50,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /docs/docs/DocDsp.jsp?id=129&amp;isOpenFirstAss=0&amp;e71441596731500=",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/docs/docs/DocDsp.jsp?id=129&isOpenFirstAss=0&e71441596731500=",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u14.png"}},
{
          "id":"a4f1beded6b44e6196e6efd5e7e77f7d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":26,
              "y":100},
            "size":{
              "width":48,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aee33bda5b6e4f43837632855e5ed393",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":26,
                  "y":100},
                "size":{
                  "width":48,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0cd408d2e1a404d866b7c74bf2ea700",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":26,
              "y":200},
            "size":{
              "width":48,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e585fb6b06164bd7b0bd6f992cb234a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":26,
                  "y":200},
                "size":{
                  "width":48,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"afc73f6163ae4e57a8631a8bc196f128",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":26,
              "y":300},
            "size":{
              "width":48,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de39cf846a904a66920ee395425d8f28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":26,
                  "y":300},
                "size":{
                  "width":48,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e3a2e5f270a49c495c183455bf9b4ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA69A9B,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1}}},
            "location":{
              "x":106,
              "y":52},
            "size":{
              "width":270,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e819b6f27bf4c6ba3025d922fab5362",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA69A9B,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1}}},
                "location":{
                  "x":106,
                  "y":52},
                "size":{
                  "width":270,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"6112132db7fd4fd59aaca5d05472d5b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":300,
              "y":100},
            "size":{
              "width":83,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b502b0fe7d39438ba4adf42cbf0aeb32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":100},
                "size":{
                  "width":83,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0df19afea314620b3eca47176c3d63d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1}}},
            "location":{
              "x":106,
              "y":152},
            "size":{
              "width":270,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"891fe145bd2e491686c7657be1bc7df5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1}}},
                "location":{
                  "x":106,
                  "y":152},
                "size":{
                  "width":270,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"d85e5b3294d749af9227257464a8729f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":300,
              "y":200},
            "size":{
              "width":83,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9996ffff8df49f79bed216f9daf4c37",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":200},
                "size":{
                  "width":83,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2c81e865e762442ab344a8529804ab99",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFA69A9B,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1}}},
            "location":{
              "x":106,
              "y":252},
            "size":{
              "width":270,
              "height":67}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"467b371b4e6f413b977e2f885204eac0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFA69A9B,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF000000,
                      "opacity":1}}},
                "location":{
                  "x":106,
                  "y":252},
                "size":{
                  "width":270,
                  "height":67}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"439d4c36c74f4b6ca1adfaf70e80420a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":300,
              "y":303},
            "size":{
              "width":83,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c5a8fbc1d03403e8c4684730aa75a15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":300,
                  "y":303},
                "size":{
                  "width":83,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ac72372f77d64944ad54f0cbe33683e6":{
      "scriptId":"u0"},
    "da0593c908cc4976b332a1ef755152f2":{
      "scriptId":"u1"},
    "9e730c1009484f7ba53b02cac02c5226":{
      "scriptId":"u2"},
    "a98a9e4948c1445fb39b22e61b10cf95":{
      "scriptId":"u3"},
    "b70ee0cb89004b15b90d198d3ab0ae6e":{
      "scriptId":"u4"},
    "dc3fe654a73548bca10ad2b3aec507f6":{
      "scriptId":"u5"},
    "89fbb1dd4edd41ee88f4e147540c5433":{
      "scriptId":"u6"},
    "f83754b1163b4d64809b722ec04338e4":{
      "scriptId":"u7"},
    "42faf4bb33c74fc8bfc46d66dc85c863":{
      "scriptId":"u8"},
    "af1d16d4dd234f2d8465be11842cc7df":{
      "scriptId":"u9"},
    "cdd807ff07f5483db2f27756828cc28b":{
      "scriptId":"u10"},
    "8e416caebb424106ad706356313435d0":{
      "scriptId":"u11"},
    "c80a1029fc054140a452cdf946f1fd16":{
      "scriptId":"u12"},
    "f22e5d0c79aa439b82992836dfaf2eb6":{
      "scriptId":"u13"},
    "20f52041e7a84e0fade7a2231893fcb9":{
      "scriptId":"u14"},
    "1a7963aeced8479cb53c13a179f7a19d":{
      "scriptId":"u15"},
    "a4f1beded6b44e6196e6efd5e7e77f7d":{
      "scriptId":"u16"},
    "aee33bda5b6e4f43837632855e5ed393":{
      "scriptId":"u17"},
    "a0cd408d2e1a404d866b7c74bf2ea700":{
      "scriptId":"u18"},
    "e585fb6b06164bd7b0bd6f992cb234a5":{
      "scriptId":"u19"},
    "afc73f6163ae4e57a8631a8bc196f128":{
      "scriptId":"u20"},
    "de39cf846a904a66920ee395425d8f28":{
      "scriptId":"u21"},
    "3e3a2e5f270a49c495c183455bf9b4ea":{
      "scriptId":"u22"},
    "8e819b6f27bf4c6ba3025d922fab5362":{
      "scriptId":"u23"},
    "6112132db7fd4fd59aaca5d05472d5b0":{
      "scriptId":"u24"},
    "b502b0fe7d39438ba4adf42cbf0aeb32":{
      "scriptId":"u25"},
    "a0df19afea314620b3eca47176c3d63d":{
      "scriptId":"u26"},
    "891fe145bd2e491686c7657be1bc7df5":{
      "scriptId":"u27"},
    "d85e5b3294d749af9227257464a8729f":{
      "scriptId":"u28"},
    "b9996ffff8df49f79bed216f9daf4c37":{
      "scriptId":"u29"},
    "2c81e865e762442ab344a8529804ab99":{
      "scriptId":"u30"},
    "467b371b4e6f413b977e2f885204eac0":{
      "scriptId":"u31"},
    "439d4c36c74f4b6ca1adfaf70e80420a":{
      "scriptId":"u32"},
    "5c5a8fbc1d03403e8c4684730aa75a15":{
      "scriptId":"u33"}}});