$axure.loadCurrentPage({
  "url":"index.html",
  "generationDate":new Date(1454067905423.65),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ee1e700130914918b784178c8064bbcb",
    "type":"Axure:Page",
    "name":"index",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b1a8fb24be3244acad5c72692bf011c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "textShadow":{
              "on":true,
              "offsetX":1,
              "offsetY":1,
              "blurRadius":1,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.647058823529412}},
            "location":{
              "x":19,
              "y":19},
            "size":{
              "width":109,
              "height":22},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"357e0cd884554f92bc729031c28fe91c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC,
                  "opacity":1},
                "textShadow":{
                  "on":true,
                  "offsetX":1,
                  "offsetY":1,
                  "blurRadius":1,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.647058823529412}},
                "location":{
                  "x":19,
                  "y":19},
                "size":{
                  "width":109,
                  "height":22},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18671e7c49354775a5ce3042ea1fa392",
          "label":"1",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'"},
              "selected":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "opacity":"0.8",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":18,
              "y":57},
            "size":{
              "width":223,
              "height":155}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b88b39b47d064f50bd224a4c05e58625",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'"},
                  "selected":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "opacity":"0.8",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":18,
                  "y":57},
                "size":{
                  "width":223,
                  "height":155}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/1_u2.jpg",
            "selected~":"images/index/1_u2_selected.png"}},
{
          "id":"e8c5287060ae40e988ca86ca85b89c5e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "opacity":"0.8",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":271,
              "y":57},
            "size":{
              "width":223,
              "height":155}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6db47c3c81424be793dabe6e87b09289",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "opacity":"0.8",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":271,
                  "y":57},
                "size":{
                  "width":223,
                  "height":155}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /docs/docs/DocDsp.jsp?id=444",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/docs/docs/DocDsp.jsp?id=444",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/u4.png",
            "mouseOver~":"images/index/u4_mouseOver.png"}},
{
          "id":"97caa9e1c9654145afd2c35223247b4b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "opacity":"0.8",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":524,
              "y":57},
            "size":{
              "width":223,
              "height":155}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac3115f37c1b4d4baa911052c2d3ff50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "opacity":"0.8",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":524,
                  "y":57},
                "size":{
                  "width":223,
                  "height":155}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /docs/docs/DocDsp.jsp?id=444",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/docs/docs/DocDsp.jsp?id=444",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/u6.jpg",
            "mouseOver~":"images/index/u6_mouseOver.png"}},
{
          "id":"181e16435a6842a8baba8ce99f4afe5b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "opacity":"0.8",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":777,
              "y":57},
            "size":{
              "width":223,
              "height":155}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce95cf0c6a924e39ac2bf7e74bd4f3ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "opacity":"0.8",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":777,
                  "y":57},
                "size":{
                  "width":223,
                  "height":155}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /docs/docs/DocDsp.jsp?id=444",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/docs/docs/DocDsp.jsp?id=444",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/u8.jpg",
            "mouseOver~":"images/index/u8_mouseOver.png"}},
{
          "id":"2ba03c6933a84cbcbb06be7c66262b25",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "opacity":"0.8"}},
            "location":{
              "x":18,
              "y":342},
            "size":{
              "width":223,
              "height":155}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ff3a8765f404380b70a15b3435d5026",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "opacity":"0.8"}},
                "location":{
                  "x":18,
                  "y":342},
                "size":{
                  "width":223,
                  "height":155}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /docs/docs/DocDsp.jsp?id=444",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/docs/docs/DocDsp.jsp?id=444",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/u10.png",
            "mouseOver~":"images/index/u10.png"}},
{
          "id":"363f9e19c1db410dac4d122fbd79a087",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "opacity":"0.8",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":271,
              "y":342},
            "size":{
              "width":223,
              "height":155}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a13e9aba0274289a46d24fce6413718",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "opacity":"0.8",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":271,
                  "y":342},
                "size":{
                  "width":223,
                  "height":155}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /docs/docs/DocDsp.jsp?id=444",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/docs/docs/DocDsp.jsp?id=444",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/u12.jpg",
            "mouseOver~":"images/index/u12_mouseOver.png"}},
{
          "id":"c55da0ee207a4aab8821616178487957",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "opacity":"0.8",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":524,
              "y":342},
            "size":{
              "width":223,
              "height":155}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93974381fdeb489a93c94f07607c2dae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "opacity":"0.8",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":524,
                  "y":342},
                "size":{
                  "width":223,
                  "height":155}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /docs/docs/DocDsp.jsp?id=444",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/docs/docs/DocDsp.jsp?id=444",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/u14.jpg",
            "mouseOver~":"images/index/u14_mouseOver.png"}},
{
          "id":"e6d1400bd34d402ea4f9f42ce37a91c7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "opacity":"0.8",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}}},
            "location":{
              "x":777,
              "y":342},
            "size":{
              "width":223,
              "height":155}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7da435b9960d4a25857d5ab8b6c6df2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "opacity":"0.8",
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":5,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}}},
                "location":{
                  "x":777,
                  "y":342},
                "size":{
                  "width":223,
                  "height":155}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 新窗口/标签页 打开 /docs/docs/DocDsp.jsp?id=444",
                      "target":{
                        "targetType":"webUrl",
                        "urlLiteral":{
                          "exprType":"stringLiteral",
                          "value":"/docs/docs/DocDsp.jsp?id=444",
                          "stos":[]},
                        "includeVariables":false},
                      "linkType":"new"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/index/u16.jpg",
            "mouseOver~":"images/index/u16_mouseOver.png"}},
{
          "id":"6e906e747ee34eda9f0d4cb435b05272",
          "label":"1",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"center",
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'"}},
            "location":{
              "x":18,
              "y":219},
            "size":{
              "width":223,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e611b82fdfdf40cc853344ffa0b66d96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'"}},
                "location":{
                  "x":18,
                  "y":219},
                "size":{
                  "width":223,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a566c8c30044937959ebf6d2adc4519",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFED9671,
                  "opacity":1}}},
            "location":{
              "x":271,
              "y":222},
            "size":{
              "width":223,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"53cb13697d6a4ee289cfbcc9ca8db71d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFED9671,
                      "opacity":1}}},
                "location":{
                  "x":271,
                  "y":222},
                "size":{
                  "width":223,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"6efff8b6ca8b42928299328fa989d43a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFED9671,
                  "opacity":1}}},
            "location":{
              "x":524,
              "y":222},
            "size":{
              "width":223,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f62f1adf5aa4ef4b9b7bf78197bec30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFED9671,
                      "opacity":1}}},
                "location":{
                  "x":524,
                  "y":222},
                "size":{
                  "width":223,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"b18932029c1648dab7ac62a2c9c696e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFED9671,
                  "opacity":1}}},
            "location":{
              "x":777,
              "y":222},
            "size":{
              "width":223,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6bd3427659624c07944638103b4d6126",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFED9671,
                      "opacity":1}}},
                "location":{
                  "x":777,
                  "y":222},
                "size":{
                  "width":223,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"04fae97050414e4b9b8ed9e8cae17636",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFED9671,
                  "opacity":1}}},
            "location":{
              "x":271,
              "y":511},
            "size":{
              "width":223,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e765ae6dad544f8a89837714d3578abf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFED9671,
                      "opacity":1}}},
                "location":{
                  "x":271,
                  "y":511},
                "size":{
                  "width":223,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"4d5bb223bee14a32bba48907c946fd34",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFED9671,
                  "opacity":1}}},
            "location":{
              "x":524,
              "y":511},
            "size":{
              "width":223,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"508861d1b26f43f58a03feb879ae9a5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFED9671,
                      "opacity":1}}},
                "location":{
                  "x":524,
                  "y":511},
                "size":{
                  "width":223,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"250688159bac425b9c04c397e0d68fc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFED9671,
                  "opacity":1}}},
            "location":{
              "x":777,
              "y":507},
            "size":{
              "width":223,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bba0d275c1d64b6e8b3a6091206b6ba3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFED9671,
                      "opacity":1}}},
                "location":{
                  "x":777,
                  "y":507},
                "size":{
                  "width":223,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"884c120ca52e4d4da82fe11ac07206fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFED9671,
                  "opacity":1}}},
            "location":{
              "x":18,
              "y":511},
            "size":{
              "width":223,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6b0938cbc6848f9acf1088c6733d3bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Applied Font Regular', 'Applied Font'",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFED9671,
                      "opacity":1}}},
                "location":{
                  "x":18,
                  "y":511},
                "size":{
                  "width":223,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"dda575bb84b847148d51521d3bf9acce",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":40},
            "size":{
              "width":980,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/index/u34_line.png"}},
{
          "id":"b5d1480d9e0d4a6ca1d183da98037307",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":18,
              "y":219},
            "size":{
              "width":48,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b1d70b5947a4adabbf9c4bbd9c541d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":18,
                  "y":219},
                "size":{
                  "width":48,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u35.png"}},
{
          "id":"4dad471f29c9466eae803125dd562cc8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":282,
              "y":219},
            "size":{
              "width":48,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3992d6617a8a410496bfdb107a6aa299",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":282,
                  "y":219},
                "size":{
                  "width":48,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u35.png"}},
{
          "id":"0413f11d078747a3b00f539972c594eb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":530,
              "y":219},
            "size":{
              "width":48,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bcfea85dd2344e8bb3fb3f24ea7f53be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":530,
                  "y":219},
                "size":{
                  "width":48,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u35.png"}},
{
          "id":"7fafd928cfee496a9959af6335d1c8cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":777,
              "y":219},
            "size":{
              "width":48,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"415b2d52712d4fa38d917da2e58e7702",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":777,
                  "y":219},
                "size":{
                  "width":48,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u35.png"}},
{
          "id":"87d686cc67d447d58e3a64a5a2d26fc5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":18,
              "y":507},
            "size":{
              "width":48,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"569a024c3749446989ed4014d0577f52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":18,
                  "y":507},
                "size":{
                  "width":48,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u35.png"}},
{
          "id":"fad96b6e78ff49d09cddb8574c575dde",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":271,
              "y":507},
            "size":{
              "width":48,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c61686525674692a6732bf0c31e8f64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":271,
                  "y":507},
                "size":{
                  "width":48,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u35.png"}},
{
          "id":"57df6824a2d544139e5c9623ac82dd02",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":524,
              "y":507},
            "size":{
              "width":48,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17849475e97442cbba35a1d05b3f4ce8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":524,
                  "y":507},
                "size":{
                  "width":48,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u35.png"}},
{
          "id":"bf81d110824e47e7b183600de418d72b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":777,
              "y":507},
            "size":{
              "width":48,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f7472e4ef034d749749a863cf327684",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":777,
                  "y":507},
                "size":{
                  "width":48,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/index/u35.png"}},
{
          "id":"2fec999221154a3ea0b1c911ee4ce4e8",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":18,
              "y":57},
            "size":{
              "width":222,
              "height":197}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 1 = &quot;true&quot;, 且<br> 选中状态值 1 = &quot;true&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["18671e7c49354775a5ce3042ea1fa392"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["6e906e747ee34eda9f0d4cb435b05272"]},
{
                                "exprType":"stringLiteral",
                                "value":"true",
                                "stos":[]}]}]}}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFunction",
                      "description":"设置 选中状态值 1 = &quot;false&quot;, 且<br> 选中状态值 1 = &quot;false&quot;",
                      "expr":{
                        "exprType":"block",
                        "subExprs":[{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["18671e7c49354775a5ce3042ea1fa392"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]},
{
                            "exprType":"fcall",
                            "functionName":"SetCheckState",
                            "arguments":[{
                                "exprType":"pathLiteral",
                                "isThis":false,
                                "isFocused":false,
                                "isTarget":false,
                                "value":["6e906e747ee34eda9f0d4cb435b05272"]},
{
                                "exprType":"stringLiteral",
                                "value":"false",
                                "stos":[]}]}]}}]}]}}}]}},
  "masters":{
},
  "objectPaths":{
    "b1a8fb24be3244acad5c72692bf011c9":{
      "scriptId":"u0"},
    "357e0cd884554f92bc729031c28fe91c":{
      "scriptId":"u1"},
    "18671e7c49354775a5ce3042ea1fa392":{
      "scriptId":"u2"},
    "b88b39b47d064f50bd224a4c05e58625":{
      "scriptId":"u3"},
    "e8c5287060ae40e988ca86ca85b89c5e":{
      "scriptId":"u4"},
    "6db47c3c81424be793dabe6e87b09289":{
      "scriptId":"u5"},
    "97caa9e1c9654145afd2c35223247b4b":{
      "scriptId":"u6"},
    "ac3115f37c1b4d4baa911052c2d3ff50":{
      "scriptId":"u7"},
    "181e16435a6842a8baba8ce99f4afe5b":{
      "scriptId":"u8"},
    "ce95cf0c6a924e39ac2bf7e74bd4f3ff":{
      "scriptId":"u9"},
    "2ba03c6933a84cbcbb06be7c66262b25":{
      "scriptId":"u10"},
    "7ff3a8765f404380b70a15b3435d5026":{
      "scriptId":"u11"},
    "363f9e19c1db410dac4d122fbd79a087":{
      "scriptId":"u12"},
    "4a13e9aba0274289a46d24fce6413718":{
      "scriptId":"u13"},
    "c55da0ee207a4aab8821616178487957":{
      "scriptId":"u14"},
    "93974381fdeb489a93c94f07607c2dae":{
      "scriptId":"u15"},
    "e6d1400bd34d402ea4f9f42ce37a91c7":{
      "scriptId":"u16"},
    "7da435b9960d4a25857d5ab8b6c6df2f":{
      "scriptId":"u17"},
    "6e906e747ee34eda9f0d4cb435b05272":{
      "scriptId":"u18"},
    "e611b82fdfdf40cc853344ffa0b66d96":{
      "scriptId":"u19"},
    "6a566c8c30044937959ebf6d2adc4519":{
      "scriptId":"u20"},
    "53cb13697d6a4ee289cfbcc9ca8db71d":{
      "scriptId":"u21"},
    "6efff8b6ca8b42928299328fa989d43a":{
      "scriptId":"u22"},
    "4f62f1adf5aa4ef4b9b7bf78197bec30":{
      "scriptId":"u23"},
    "b18932029c1648dab7ac62a2c9c696e6":{
      "scriptId":"u24"},
    "6bd3427659624c07944638103b4d6126":{
      "scriptId":"u25"},
    "04fae97050414e4b9b8ed9e8cae17636":{
      "scriptId":"u26"},
    "e765ae6dad544f8a89837714d3578abf":{
      "scriptId":"u27"},
    "4d5bb223bee14a32bba48907c946fd34":{
      "scriptId":"u28"},
    "508861d1b26f43f58a03feb879ae9a5f":{
      "scriptId":"u29"},
    "250688159bac425b9c04c397e0d68fc5":{
      "scriptId":"u30"},
    "bba0d275c1d64b6e8b3a6091206b6ba3":{
      "scriptId":"u31"},
    "884c120ca52e4d4da82fe11ac07206fa":{
      "scriptId":"u32"},
    "a6b0938cbc6848f9acf1088c6733d3bf":{
      "scriptId":"u33"},
    "dda575bb84b847148d51521d3bf9acce":{
      "scriptId":"u34"},
    "b5d1480d9e0d4a6ca1d183da98037307":{
      "scriptId":"u35"},
    "5b1d70b5947a4adabbf9c4bbd9c541d4":{
      "scriptId":"u36"},
    "4dad471f29c9466eae803125dd562cc8":{
      "scriptId":"u37"},
    "3992d6617a8a410496bfdb107a6aa299":{
      "scriptId":"u38"},
    "0413f11d078747a3b00f539972c594eb":{
      "scriptId":"u39"},
    "bcfea85dd2344e8bb3fb3f24ea7f53be":{
      "scriptId":"u40"},
    "7fafd928cfee496a9959af6335d1c8cd":{
      "scriptId":"u41"},
    "415b2d52712d4fa38d917da2e58e7702":{
      "scriptId":"u42"},
    "87d686cc67d447d58e3a64a5a2d26fc5":{
      "scriptId":"u43"},
    "569a024c3749446989ed4014d0577f52":{
      "scriptId":"u44"},
    "fad96b6e78ff49d09cddb8574c575dde":{
      "scriptId":"u45"},
    "7c61686525674692a6732bf0c31e8f64":{
      "scriptId":"u46"},
    "57df6824a2d544139e5c9623ac82dd02":{
      "scriptId":"u47"},
    "17849475e97442cbba35a1d05b3f4ce8":{
      "scriptId":"u48"},
    "bf81d110824e47e7b183600de418d72b":{
      "scriptId":"u49"},
    "4f7472e4ef034d749749a863cf327684":{
      "scriptId":"u50"},
    "2fec999221154a3ea0b1c911ee4ce4e8":{
      "scriptId":"u51"}}});