$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1443403164536.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b936ff3d351c4adbb214c35af557e03c",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
      "a":{
}},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0db5e56ddf83408fa50cfdc5ed6ed4f4",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
            "a":{
}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"57799c400f7d4a31b663c46e00f85654",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"b247f17ac4ae4ebb82e3c6dda22e95ce",
                  "label":"",
                  "parentDynamicPanel":"0db5e56ddf83408fa50cfdc5ed6ed4f4",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":890,
                      "height":226}},
                  "adaptiveStyles":{
                    "a":{
                      "limbo":true}},
                  "objects":[{
                      "id":"8c5d692ecad1444f9db6a0cc40a4963b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0db5e56ddf83408fa50cfdc5ed6ed4f4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":890,
                          "height":226}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/home/u1.png",
                    "normal~a":"images/home/u1.png"}},
{
                  "id":"fc1603c690094a7a909eb51470dd37b3",
                  "label":"",
                  "parentDynamicPanel":"0db5e56ddf83408fa50cfdc5ed6ed4f4",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":20},
                    "size":{
                      "width":745,
                      "height":228},
                    "limbo":true},
                  "adaptiveStyles":{
                    "a":{
                      "location":{
                        "x":0,
                        "y":0},
                      "limbo":false}},
                  "objects":[{
                      "id":"c688e82d9284401781ed19c0e711d62c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0db5e56ddf83408fa50cfdc5ed6ed4f4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":20},
                        "size":{
                          "width":745,
                          "height":228},
                        "limbo":true},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/home/u3.jpg",
                    "normal~a":"images/home/u3.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
                "a":{
}}},
{
              "id":"43a2443027ff4d86b18468bc7cb72911",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"2117b9f69cec44f0bde1c5cde02a30bc",
                  "label":"",
                  "parentDynamicPanel":"0db5e56ddf83408fa50cfdc5ed6ed4f4",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":-8},
                    "size":{
                      "width":745,
                      "height":228}},
                  "adaptiveStyles":{
                    "a":{
}},
                  "objects":[{
                      "id":"2c9063a2fc1b472b8ddff33c59f98f70",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0db5e56ddf83408fa50cfdc5ed6ed4f4",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":0,
                          "y":-8},
                        "size":{
                          "width":745,
                          "height":228}},
                      "adaptiveStyles":{
                        "a":{
}}}],
                  "images":{
                    "normal~":"images/home/u3.jpg"}}],
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "image":null,
                "imageHorizontalAlignment":"near",
                "imageVerticalAlignment":"near",
                "imageRepeat":"auto"},
              "adaptiveStyles":{
                "a":{
}}}]},
{
          "id":"755a62620336436cb4fe6c9769e6d82c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":745,
              "height":228},
            "limbo":true},
          "adaptiveStyles":{
            "a":{
}},
          "objects":[{
              "id":"b991fa67cde34d23893798b936a789d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":745,
                  "height":228},
                "limbo":true},
              "adaptiveStyles":{
                "a":{
}}}],
          "images":{
            "normal~":"images/home/u3.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "0db5e56ddf83408fa50cfdc5ed6ed4f4":{
      "scriptId":"u0"},
    "b247f17ac4ae4ebb82e3c6dda22e95ce":{
      "scriptId":"u1"},
    "8c5d692ecad1444f9db6a0cc40a4963b":{
      "scriptId":"u2"},
    "fc1603c690094a7a909eb51470dd37b3":{
      "scriptId":"u3"},
    "c688e82d9284401781ed19c0e711d62c":{
      "scriptId":"u4"},
    "2117b9f69cec44f0bde1c5cde02a30bc":{
      "scriptId":"u5"},
    "2c9063a2fc1b472b8ddff33c59f98f70":{
      "scriptId":"u6"},
    "755a62620336436cb4fe6c9769e6d82c":{
      "scriptId":"u7"},
    "b991fa67cde34d23893798b936a789d0":{
      "scriptId":"u8"}}});